name: Sancraft-Core
version: ${project.version}
main: de.davidcraft.sanoj.core.main
api-version: 1.17
authors: [ DavidCraft ]
description: Server Core Plugin für Sanoj
website: https://davidcraft.de

commands:
  ram:
    description: Ram Usage Command
    aliases: randomacesmemory
  regeln:
    description: View the Rules
    aliases: rules
  modinstaller:
    description: anweswnd
    aliases: mi
  softwareinstaller:
    description: amwesemd
    aliases: ai
  control:
    description: test
  stopcontrol:
    description: test

permissions:
  prefix:
    prefix.admin:
    description: Set Prefix Color
