name: SanCraft-Core
version: ${project.version}
main: dev.sancraft.core.main
api-version: 1.17
authors: [ DavidCraft ]
description: Server Core Plugin für das SanCraft-Netzwerk
website: https://sancraft.dev

commands:
  ram:
    description: Ram Usage Command
    aliases: randomacesmemory
  regeln:
    description: View the Rules
    aliases: rules
  modinstaller:
    description: anweswnd
    aliases: mi
  softwareinstaller:
    description: amwesemd
    aliases: ai

permissions:
  prefix:
    prefix.admin:
    description: Set Prefix Color
