name: SanCraft-Core
version: ${project.version}
main: dev.sancraft.core.main
api-version: 1.17
authors: [ DavidCraft ]
description: Server Core Plugin für das SanCraft-Netzwerk
website: https://sancraft.dev

commands:
  ram:
    aliases: randomacesmemory
  regeln:
    aliases: rules
  modinstaller:
    aliases: mi
  softwareinstaller:
    aliases: ai
  discord:
    aliases: dc
  twitter:
    aliases: tw
  github:
    aliases: gh
  website:
    aliases: web

permissions:
  prefix:
    prefix.admin:
    description: Set Prefix Color
